// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCz8P0FwaqQb-lyX5gXAhOpTtQ6MTFYGlI',
    appId: '1:14583679277:web:e234805d604c4eb16e6ba4',
    messagingSenderId: '14583679277',
    projectId: 'task-management-apps-870d1',
    authDomain: 'task-management-apps-870d1.firebaseapp.com',
    storageBucket: 'task-management-apps-870d1.appspot.com',
    measurementId: 'G-2GP7HMLJNK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAiTwxegtMfSopgynHD6PobhUTiR6PeKjs',
    appId: '1:14583679277:android:a7495618b48e50c66e6ba4',
    messagingSenderId: '14583679277',
    projectId: 'task-management-apps-870d1',
    storageBucket: 'task-management-apps-870d1.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCua1S8_V0TSed6ipzsrSqY4GqJvmcmZvs',
    appId: '1:14583679277:ios:7d7fb4c1de74028b6e6ba4',
    messagingSenderId: '14583679277',
    projectId: 'task-management-apps-870d1',
    storageBucket: 'task-management-apps-870d1.appspot.com',
    androidClientId:
        '14583679277-2ulv019ifsr2koctvnqe24mo34m1vm7p.apps.googleusercontent.com',
    iosClientId:
        '14583679277-93119rebumak46ghldjkmeqnshd6ersr.apps.googleusercontent.com',
    iosBundleId: 'com.example.taskManagementApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCua1S8_V0TSed6ipzsrSqY4GqJvmcmZvs',
    appId: '1:14583679277:ios:7d7fb4c1de74028b6e6ba4',
    messagingSenderId: '14583679277',
    projectId: 'task-management-apps-870d1',
    storageBucket: 'task-management-apps-870d1.appspot.com',
    androidClientId:
        '14583679277-2ulv019ifsr2koctvnqe24mo34m1vm7p.apps.googleusercontent.com',
    iosClientId:
        '14583679277-93119rebumak46ghldjkmeqnshd6ersr.apps.googleusercontent.com',
    iosBundleId: 'com.example.taskManagementApp',
  );
}
